
# Visceral adipose tissuen(kg)
summary(lm(visceral.adipose.tissue.value~BMIscan,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~BMIscan + Age,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat, function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~Waist.girth..cm., function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~Waist.girth..cm. + Age, function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~WHtR,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~WHtR + Age,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~WHtR + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~ Waist.girth..cm. + Hip.girth..cm. + WHR + Volume.Belly..l. + Volume.Hip..l.,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~ Waist.girth..cm. + Hip.girth..cm. + WHR + Volume.Belly..l. + Volume.Hip..l. + Age,function_data_analysis(Sexv="M")))
summary(lm(visceral.adipose.tissue.value~ Waist.girth..cm. + Hip.girth..cm. + WHR + Volume.Belly..l. + Volume.Hip..l. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))


summary(lm(visceral.adipose.tissue.value~BMIscan,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~BMIscan + Age,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~BMIscan + Age + Education_cat + Physical.Activity_cat +Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~Waist.girth..cm.,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~Waist.girth..cm. +Age,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat +Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~WHtR, function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~WHtR + Age,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~WHtR + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~ Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + Upper.arm.girth.left..cm. +Thigh.girth.left..horizontal...cm. + WHR + Volume.Hip..l.,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~ Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + Upper.arm.girth.left..cm. +Thigh.girth.left..horizontal...cm. + WHR + Volume.Hip..l.+ Age,function_data_analysis(Sexv="F")))
summary(lm(visceral.adipose.tissue.value~ Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + Upper.arm.girth.left..cm. +Thigh.girth.left..horizontal...cm. + WHR + Volume.Hip..l. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))



# Relative fat mass (%)
summary(lm(Relative.fat.mass.value~BMIscan,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~BMIscan + Age,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~Waist.girth..cm.,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~Waist.girth..cm. + Age,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~WHtR,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~WHtR + Age, function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~WHtR + Age + Education_cat + Physical.Activity_cat +Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~ Body.height..cm. + Mid.neck.girth..cm. + High.waist.girth..cm. + Maximum.belly.circumference..cm. + Forearm.girth.left..cm. + WHR + Volume.Thigh.Left..l. + Volume.Chest..l. + Volume.Belly..l. + Volume.Hip..l.,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~ Body.height..cm. + Mid.neck.girth..cm. + High.waist.girth..cm. + Maximum.belly.circumference..cm. + Forearm.girth.left..cm. + WHR + Volume.Thigh.Left..l. + Volume.Chest..l. + Volume.Belly..l. + Volume.Hip..l. + Age,function_data_analysis(Sexv="M")))
summary(lm(Relative.fat.mass.value~ Body.height..cm. + Mid.neck.girth..cm. + High.waist.girth..cm. + Maximum.belly.circumference..cm. + Forearm.girth.left..cm. + WHR + Volume.Thigh.Left..l. + Volume.Chest..l. + Volume.Belly..l. + Volume.Hip..l. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))


summary(lm(Relative.fat.mass.value~BMIscan,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~BMIscan + Age,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~Waist.girth..cm.,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~Waist.girth..cm. + Age,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~WHtR,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~WHtR + Age,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~WHtR + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~ Mid.neck.girth..cm. + Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + High.waist.girth..cm. + Hip.girth..cm. + Upper.arm.girth.left..cm. + WHtR + WHR  + Volume.Belly..l. + Volume.Hip..l. + BMIscan,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~ Mid.neck.girth..cm. + Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + High.waist.girth..cm. + Hip.girth..cm. + Upper.arm.girth.left..cm. + WHtR + WHR  + Volume.Belly..l. + Volume.Hip..l. + BMIscan+ Age,function_data_analysis(Sexv="F")))
summary(lm(Relative.fat.mass.value~ Mid.neck.girth..cm. + Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + High.waist.girth..cm. + Hip.girth..cm. + Upper.arm.girth.left..cm. + WHtR + WHR  + Volume.Belly..l. + Volume.Hip..l. + BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))

# Skeletal muscle mass index (kg/m2)
summary(lm(SMI~BMIscan,function_data_analysis(Sexv="M")))
summary(lm(SMI~BMIscan + Age,function_data_analysis(Sexv="M")))
summary(lm(SMI~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(SMI~Waist.girth..cm.,function_data_analysis(Sexv="M")))
summary(lm(SMI~Waist.girth..cm. + Age,function_data_analysis(Sexv="M")))
summary(lm(SMI~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(SMI~WHtR,function_data_analysis(Sexv="M")))
summary(lm(SMI~WHtR + Age,function_data_analysis(Sexv="M")))
summary(lm(SMI~Forearm.girth.left..cm.,function_data_analysis(Sexv="M")))
summary(lm(SMI~Forearm.girth.left..cm. + Age,function_data_analysis(Sexv="M")))
summary(lm(SMI~Forearm.girth.left..cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(SMI~Thigh.girth.left..horizontal...cm.,function_data_analysis(Sexv="M")))
summary(lm(SMI~Thigh.girth.left..horizontal...cm. + Age,function_data_analysis(Sexv="M")))
summary(lm(SMI~Thigh.girth.left..horizontal...cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(SMI~WHtR + Age +  Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(SMI~Maximum.belly.circumference..cm.+ Forearm.girth.left..cm. + Thigh.girth.left..horizontal...cm. + Volume.Thigh.Left..l.+ Volume.Chest..l.+ Volume.Belly..l.+ Volume.Hip..l.+ BMIscan,function_data_analysis(Sexv="M")))
summary(lm(SMI~Maximum.belly.circumference..cm.+ Forearm.girth.left..cm. + Thigh.girth.left..horizontal...cm. + Volume.Thigh.Left..l.+ Volume.Chest..l.+ Volume.Belly..l.+ Volume.Hip..l.+ BMIscan + Age,function_data_analysis(Sexv="M")))
summary(lm(SMI~Maximum.belly.circumference..cm.+ Forearm.girth.left..cm. + Thigh.girth.left..horizontal...cm. + Volume.Thigh.Left..l.+ Volume.Chest..l.+ Volume.Belly..l.+ Volume.Hip..l.+ BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))


summary(lm(SMI~BMIscan,function_data_analysis(Sexv="F")))
summary(lm(SMI~BMIscan + Age,function_data_analysis(Sexv="F")))
summary(lm(SMI~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(SMI~Waist.girth..cm.,function_data_analysis(Sexv="F")))
summary(lm(SMI~Waist.girth..cm. + Age,function_data_analysis(Sexv="F")))
summary(lm(SMI~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(SMI~WHtR,function_data_analysis(Sexv="F")))
summary(lm(SMI~WHtR + Age,function_data_analysis(Sexv="F")))
summary(lm(SMI~WHtR + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(SMI~Forearm.girth.left..cm.,function_data_analysis(Sexv="F")))
summary(lm(SMI~Forearm.girth.left..cm. + Age,function_data_analysis(Sexv="F")))
summary(lm(SMI~Forearm.girth.left..cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
summary(lm(SMI~Thigh.girth.left..horizontal...cm.,function_data_analysis(Sexv="F")))
summary(lm(SMI~Thigh.girth.left..horizontal...cm. + Age,function_data_analysis(Sexv="F")))
summary(lm(SMI~Thigh.girth.left..horizontal...cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M")))
summary(lm(SMI~  Waist.girth..cm. + WHtR + Mid.neck.girth..cm. + Cross.shoulder.over.neck..cm.+  Volume.Thigh.Left..l.+ Volume.Hip..l.+BMIscan ,function_data_analysis(Sexv="F")))
summary(lm(SMI~ Waist.girth..cm. + WHtR + Mid.neck.girth..cm. + Cross.shoulder.over.neck..cm.+  Volume.Thigh.Left..l.+ Volume.Hip..l.+BMIscan+ Age,function_data_analysis(Sexv="F")))
summary(lm(SMI~ Waist.girth..cm. + WHtR + Mid.neck.girth..cm. + Cross.shoulder.over.neck..cm.+  Volume.Thigh.Left..l.+ Volume.Hip..l.+BMIscan+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F")))
