
# Visceral adipose tissuen(kg)
## male
train(visceral.adipose.tissue.value~Age,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)


train(visceral.adipose.tissue.value~Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~BMIscan,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~BMIscan + Age,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat, data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Waist.girth..cm., data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Waist.girth..cm. + Age, function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~WHtR,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~WHtR + Age,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~WHtR + Age + Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~ Waist.girth..cm. + Hip.girth..cm. + WHR + Volume.Belly..l. + Volume.Hip..l.,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~ Waist.girth..cm. + Hip.girth..cm. + WHR + Volume.Belly..l. + Volume.Hip..l. + Age,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~ Waist.girth..cm. + Hip.girth..cm. + WHR + Volume.Belly..l. + Volume.Hip..l. + Age + Education_cat + Physical.Activity_cat + Diet_cat,
      data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)

## female
train(visceral.adipose.tissue.value~Age,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~BMIscan,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~BMIscan + Age,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat, data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Waist.girth..cm., data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Waist.girth..cm. + Age, function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~WHtR,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~WHtR + Age,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~WHtR + Age + Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(visceral.adipose.tissue.value~ Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + Upper.arm.girth.left..cm. +Thigh.girth.left..horizontal...cm. + WHR + Volume.Hip..l. +Hip.girth..cm.,data=function_data_analysis(Sexv="F"),method = "lm", trControl =  boot_val)
train(visceral.adipose.tissue.value~ Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + Upper.arm.girth.left..cm. +Thigh.girth.left..horizontal...cm. + WHR + Volume.Hip..l.+Hip.girth..cm. + Age,data=function_data_analysis(Sexv="F"),method = "lm", trControl =  boot_val)
train(visceral.adipose.tissue.value~ Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + Upper.arm.girth.left..cm. +Thigh.girth.left..horizontal...cm. + WHR + Volume.Hip..l.+Hip.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,
      data=function_data_analysis(Sexv="F"),method = "lm", trControl =  boot_val)

# Relative fat mass (%)
## male
train(Relative.fat.mass.value~Age,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~BMIscan,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~BMIscan + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Waist.girth..cm.,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Waist.girth..cm. + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~WHtR,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~WHtR + Age, function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~WHtR + Age + Education_cat + Physical.Activity_cat +Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~ Body.height..cm. + Mid.neck.girth..cm. + High.waist.girth..cm. + Maximum.belly.circumference..cm. + Forearm.girth.left..cm. + WHR + Volume.Thigh.Left..l. + Volume.Chest..l. + Volume.Belly..l. + Volume.Hip..l.,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~ Body.height..cm. + Mid.neck.girth..cm. + High.waist.girth..cm. + Maximum.belly.circumference..cm. + Forearm.girth.left..cm. + WHR + Volume.Thigh.Left..l. + Volume.Chest..l. + Volume.Belly..l. + Volume.Hip..l. + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~ Body.height..cm. + Mid.neck.girth..cm. + High.waist.girth..cm. + Maximum.belly.circumference..cm. + Forearm.girth.left..cm. + WHR + Volume.Thigh.Left..l. + Volume.Chest..l. + Volume.Belly..l. + Volume.Hip..l. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)


train(Relative.fat.mass.value~Age,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~BMIscan,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~BMIscan + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Waist.girth..cm.,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Waist.girth..cm. + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~WHtR,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~WHtR + Age, function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~WHtR + Age + Education_cat + Physical.Activity_cat +Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~ Mid.neck.girth..cm. + Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + High.waist.girth..cm. + Hip.girth..cm. + Upper.arm.girth.left..cm. + WHtR + WHR  + Volume.Belly..l. + Volume.Hip..l. + BMIscan,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~ Mid.neck.girth..cm. + Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + High.waist.girth..cm. + Hip.girth..cm. + Upper.arm.girth.left..cm. + WHtR + WHR  + Volume.Belly..l. + Volume.Hip..l. + BMIscan+ Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(Relative.fat.mass.value~ Mid.neck.girth..cm. + Bust.chest.girth..horizontal...cm. + Neck.to.waist.center.back..cm. + Waist.girth..cm. + High.waist.girth..cm. + Hip.girth..cm. + Upper.arm.girth.left..cm. + WHtR + WHR  + Volume.Belly..l. + Volume.Hip..l. + BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)

# Skeletal muscle mass index (kg/m2)
## male
train(SMI~Age,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~BMIscan,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~BMIscan + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Waist.girth..cm.,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Waist.girth..cm. + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~WHtR,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~WHtR + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~WHtR + Age +  Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Forearm.girth.left..cm.,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Forearm.girth.left..cm. + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Forearm.girth.left..cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Thigh.girth.left..horizontal...cm.,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Thigh.girth.left..horizontal...cm. + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Thigh.girth.left..horizontal...cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Maximum.belly.circumference..cm.+ Forearm.girth.left..cm. + Thigh.girth.left..horizontal...cm. + Volume.Thigh.Left..l.+ Volume.Chest..l.+ Volume.Belly..l.+ Volume.Hip..l.+ BMIscan,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Maximum.belly.circumference..cm.+ Forearm.girth.left..cm. + Thigh.girth.left..horizontal...cm. + Volume.Thigh.Left..l.+ Volume.Chest..l.+ Volume.Belly..l.+ Volume.Hip..l.+ BMIscan + Age,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)
train(SMI~Maximum.belly.circumference..cm.+ Forearm.girth.left..cm. + Thigh.girth.left..horizontal...cm. + Volume.Thigh.Left..l.+ Volume.Chest..l.+ Volume.Belly..l.+ Volume.Hip..l.+ BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="M"),method = "lm", trControl = boot_val)

## female
train(SMI~Age,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Education_cat + Physical.Activity_cat + Diet_cat,data=function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~BMIscan,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~BMIscan + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~BMIscan + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Waist.girth..cm.,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Waist.girth..cm. + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Waist.girth..cm. + Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~WHtR,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~WHtR + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~WHtR + Age +  Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Forearm.girth.left..cm.,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Forearm.girth.left..cm. + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Forearm.girth.left..cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Thigh.girth.left..horizontal...cm.,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Thigh.girth.left..horizontal...cm. + Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~Thigh.girth.left..horizontal...cm.+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~ Waist.girth..cm. + WHtR + Mid.neck.girth..cm. + Cross.shoulder.over.neck..cm.+ Volume.Hip..l.+BMIscan ,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~ Waist.girth..cm. + WHtR + Mid.neck.girth..cm. + Cross.shoulder.over.neck..cm.+ Volume.Hip..l.+BMIscan+ Age,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
train(SMI~ Waist.girth..cm. + WHtR + Mid.neck.girth..cm. + Cross.shoulder.over.neck..cm.+ Volume.Hip..l.+BMIscan+ Age + Education_cat + Physical.Activity_cat + Diet_cat,function_data_analysis(Sexv="F"),method = "lm", trControl = boot_val)
